### ISSUE TITLE
Decorate

### ISSUE THREAD

**Issue by Nutcha0751** [Nutcha0751/dobby#10]

**Comment by Nutcha0751** [comment]
![PK jpg](https://github.com/Nutcha0751/dobby/assets/141798062/0b91036a-c1a4-4087-9a93-c50eec13b7c6)

**Comment by Sweetypie28** [comment]
![Uploading 18B38DBA-BF52-43B6-B587-DB65BFD2396E.jpeg…]()

**Comment by Sweetypie28** [comment]
![77C8DB5D-DB27-455F-B263-F22C8642710F](https://github.com/Nutcha0751/dobby/assets/141814482/d894a202-9371-4c00-a4fe-e9eb14eba847)

**Comment by Sweetypie28** [comment]
![Uploading 08C6629F-3309-484E-ABE0-A68286D26B86.jpeg…]()

**Comment by Sweetypie28** [comment]
![Uploading 97522B45-5DB5-415B-8D0F-2A8A51C5F5B7.jpeg…]()

**Comment by Sweetypie28** [comment]
![Uploading 251954B2-2CB4-48B5-B270-7177052D499D.jpeg…]()

**Comment by Sweetypie28** [comment]
![Uploading 5268D68F-8BA9-49F6-9B07-47BF462FACBC.jpeg…]()

**Comment by Sweetypie28** [comment]
![Uploading 34D6178F-9029-4D76-BD12-F96B246F1005.jpeg…]()

**Comment by Sweetypie28** [comment]
![42973643-5EC9-4701-908B-F0241C32F3A5](https://github.com/Nutcha0751/dobby/assets/141814482/938ba5b4-1196-4efd-b865-ad435493d7ef)

**Comment by Nutcha0751** [comment]
เปลี่ยนสีตัวหนังสือ >> https://github.com/AhoyDev/Rubens-Engine/blob/master/ModuleEditor.cpp
How can I change text color of my InputText in ImGui? >> https://stackoverflow.com/questions/61853584/how-can-i-change-text-color-of-my-inputtext-in-imgui

**Comment by Nutcha0751** [comment]
//Adjust the text to be centered on the screen.
float textWidth = ImGui::CalcTextSize("Dobby's Calculator").x;
float windowWidth = ImGui::GetWindowWidth();
float centerPosX = (windowWidth - textWidth) / 2.0f;
ImGui::SetCursorPosX(centerPosX);

//Adjust font size
ImGui::SetWindowFontScale(2.0f);
ImGui::Text("Dobby's Calculator");
ImGui::SetWindowFontScale(1.0f);
