### ISSUE TITLE
รายงานปัญหา/บัค

### ISSUE THREAD

**Issue by Sweetypie28** [Nutcha0751/dobby#15]
เจอปัญหาอะไรบ้างเอ่ยย??

**Comment by Sweetypie28** [comment]
![39E22CF4-5217-4E54-B16C-038CD49F3C7A](https://github.com/Nutcha0751/dobby/assets/141814482/19fa9f0b-a2cd-474e-8155-fb7bdc30ccfe)

**Comment by Sweetypie28** [comment]
> ![39E22CF4-5217-4E54-B16C-038CD49F3C7A](https://private-user-images.githubusercontent.com/141814482/308255430-19fa9f0b-a2cd-474e-8155-fb7bdc30ccfe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNTEzMTgsIm5iZiI6MTcwOTA1MTAxOCwicGF0aCI6Ii8xNDE4MTQ0ODIvMzA4MjU1NDMwLTE5ZmE5ZjBiLWEyY2QtNDc0ZS04MTU1LWZiN2JkYzMwY2NmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QxNjIzMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMTQzYWFhMGRmYmM0MTZkYWYxNzJhZTE2YTlhZTI4NzMwMTQ5Mjc3NTJiZGY1Y2VhNWI4YjhlNTgyMzQwYmQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dpWo1I46FgMc4s-0lq843AlYXHjjttloRZlcmwd1Zeo)

- Edit เสร็จแล้วสมการเดิมไม่หายไป/สมการใหม่เด้งมา
- ปุ่มdeleteเพิ่มเป็นสองอัน
- เปลี่ยนสีปุ่ม delete

*update : เปลี่ยนสีปุ่ม delete&saveละจ้า

**Comment by Sweetypie28** [comment]
เปลี่ยนละจ้า

**Comment by Sweetypie28** [comment]
![Uploading CC36C384-7CB0-4BC7-B83D-3CA6D6439FC5.png…]()

**Comment by Sweetypie28** [comment]
![Uploading 4D9C4060-8FD7-44E5-A06B-64FA3713C508.png…]()

**Comment by Sweetypie28** [comment]
![87C426A5-8750-4919-8601-79A18E591503](https://github.com/Nutcha0751/dobby/assets/141814482/f241f1f2-a5ad-4e21-a7d6-abcbbf46ffc3)

**Comment by Sweetypie28** [comment]
> ![87C426A5-8750-4919-8601-79A18E591503](https://private-user-images.githubusercontent.com/141814482/308860685-f241f1f2-a5ad-4e21-a7d6-abcbbf46ffc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxOTc1ODIsIm5iZiI6MTcwOTE5NzI4MiwicGF0aCI6Ii8xNDE4MTQ0ODIvMzA4ODYwNjg1LWYyNDFmMWYyLWE1YWQtNGUyMS1hN2Q2LWFiY2JiZjQ2ZmZjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOVQwOTAxMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDgxMGY1MmRiZmVlNTgwOTZmNzVlNTA4MGYwZmY5MTc5MzFkNjMwYzNmNjEzNzI0MTgzNzIwNDE3ZGM3NGEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.17oBfviVJrf57aihOrWnjAG_rqiN1amIXYhPSBx5uCU)

💥💥ยกกำลัง0.5 มีปัญหา

**Comment by Korn-Sriwattana** [comment]
ไม่ทำtagแล้ว

**Comment by Korn-Sriwattana** [comment]
ไม่ทำsearch barแล้ว
