### ISSUE TITLE
slide for presentation

### ISSUE THREAD

**Issue by OnUr-KB** [Nutcha0751/dobby#16]
[[https://www.canva.com/design/DAF-KX4ytYk/3RXV56mjELaN5n5Co-S0_Q/edit?utm_content=DAF-KX4ytYk&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton](url)](https://www.canva.com/design/DAF-KX4ytYk/3RXV56mjELaN5n5Co-S0_Q/edit?utm_content=DAF-KX4ytYk&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

**Comment by Korn-Sriwattana** [comment]
ทำสไล์ดเสร็จแล้ว
