### ISSUE TITLE
แปะข้อมูล (UX/UI)

### ISSUE THREAD

**Issue by Nutcha0751** [Nutcha0751/dobby#4]
# WinForms
1. The Free Ultimate UI Design Tool for Windows Forms | C# Tutorial -> https://www.youtube.com/watch?v=IF2HHacgjAU
2. WinForms Tutorial : WinForms UI design in Visual studio 2019 | Guna UI | Sign Up | Login | C# WPF -> https://www.youtube.com/watch?v=BJQfT_1luho
3. C++ GUI: Modern Sign in Form Design (FULL) | WinForms -> https://www.youtube.com/watch?v=b8R5D0lryq0

# Walnut
How can I change text color of my InputText in ImGui? -> https://stackoverflow.com/questions/61853584/how-can-i-change-text-color-of-my-inputtext-in-imgui

# อธิบายโปรแกรม by Pai
https://archiash.notion.site/28453808e764446691e5dbc8d0578378

**Comment by Nutcha0751** [comment]
ตัวอย่าง
![1](https://github.com/Nutcha0751/dobby/assets/141798062/0e0919b6-bb4f-4aee-a53e-72ac9297f269)
![2](https://github.com/Nutcha0751/dobby/assets/141798062/63d67902-0fae-4d7c-b0e9-7f8546ca33d8)
![3](https://github.com/Nutcha0751/dobby/assets/141798062/d2477892-a4be-407b-8be4-4431c6c01280)

**Comment by Sweetypie28** [comment]
"workbench.colorCustomizations": {
    "[Theme Name]": {
        "button.background": "#ff0000",
        "button.foreground": "#ffffff"
    }
}

**Comment by Nutcha0751** [comment]
เปลี่ยนสีตัวหนังสือ >> https://github.com/AhoyDev/Rubens-Engine/blob/master/ModuleEditor.cpp
How can I change text color of my InputText in ImGui? >> https://stackoverflow.com/questions/61853584/how-can-i-change-text-color-of-my-inputtext-in-imgui
วิธี merge >> https://learn.microsoft.com/th-th/visualstudio/version-control/git-resolve-conflicts?view=vs-2022
